<?php
declare(strict_types=1); namespace Database\Seeders;
use App\Modules\Foundation\Domain\Models\Tenant; use App\Modules\Catalog\Domain\Models\{Brand,ProductCategory,Unit}; use App\Modules\Commercial\Domain\Models\{PaymentMethod,PaymentTerm}; use Illuminate\Database\Seeder;
final class GeneralCatalogSeeder extends Seeder { public function run(): void { foreach(Tenant::query()->get() as $tenant){
 foreach([['UN','Unidade','UN',0],['KG','Quilograma','KG',3],['TON','Tonelada','TON',3],['M','Metro','M',3],['M2','Metro quadrado','M²',3],['M3','Metro cúbico','M³',3],['L','Litro','L',3],['CX','Caixa','CX',0],['SC','Saco','SC',0],['PC','Peça','PÇ',0],['H','Hora','H',2],['DIA','Dia','DIA',0],['MES','Mês','MÊS',0]] as $r) Unit::withTrashed()->updateOrCreate(['tenant_id'=>$tenant->id,'code'=>$r[0]],['name'=>$r[1],'symbol'=>$r[2],'decimal_places'=>$r[3],'status'=>'active','deleted_at'=>null]);
 foreach(['3M','Bosch','Caterpillar','Gerdau','Komatsu','Makita','Mercedes-Benz','Pirelli','Tigre','Vonder','Volvo'] as $i=>$name) Brand::withTrashed()->updateOrCreate(['tenant_id'=>$tenant->id,'code'=>'MAR-'.str_pad((string)($i+1),3,'0',STR_PAD_LEFT)],['name'=>$name,'status'=>'active','deleted_at'=>null]);
 foreach([['PIX','PIX','pix',true],['BOL','Boleto bancário','boleto',true],['TED','Transferência bancária','bank_transfer',true],['DIN','Dinheiro','cash',false],['CC','Cartão de crédito','credit_card',false],['CD','Cartão de débito','debit_card',false],['CHQ','Cheque','check',true]] as $r) PaymentMethod::withTrashed()->updateOrCreate(['tenant_id'=>$tenant->id,'code'=>$r[0]],['name'=>$r[1],'type'=>$r[2],'requires_bank_data'=>$r[3],'status'=>'active','deleted_at'=>null]);
 foreach([['AV','À vista',1,0,0,true],['7D','7 dias',1,7,0,false],['15D','15 dias',1,15,0,false],['28D','28 dias',1,28,0,false],['30D','30 dias',1,30,0,false],['30-60','30/60 dias',2,30,30,false],['30-60-90','30/60/90 dias',3,30,30,false],['ENT-30','Entrada + 30 dias',2,0,30,false]] as $r) PaymentTerm::withTrashed()->updateOrCreate(['tenant_id'=>$tenant->id,'code'=>$r[0]],['name'=>$r[1],'installments'=>$r[2],'first_due_days'=>$r[3],'interval_days'=>$r[4],'is_cash'=>$r[5],'status'=>'active','deleted_at'=>null]);
 foreach([['MAT','Materiais de construção'],['PEC','Peças e manutenção'],['EPI','Equipamentos de proteção'],['COMB','Combustíveis e lubrificantes'],['SER','Serviços'],['PRE','Pré-moldados'],['ELE','Materiais elétricos'],['HID','Materiais hidráulicos']] as $r) ProductCategory::withTrashed()->updateOrCreate(['tenant_id'=>$tenant->id,'code'=>$r[0]],['name'=>$r[1],'status'=>'active','deleted_at'=>null]);
 }} }
