<?php
declare(strict_types=1);
namespace App\Filament\Resources\StockMovements;
use App\Filament\Resources\StockMovements\Pages\{CreateStockMovement,EditStockMovement,ListStockMovements}; use App\Modules\Inventory\Domain\Models\StockMovement; use BackedEnum; use UnitEnum;
use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Schemas\Components\{Grid,Section}; use Filament\Forms\Components\{DateTimePicker,Select,Textarea,TextInput}; use Filament\Tables\Table; use Filament\Tables\Columns\TextColumn; use Filament\Actions\{EditAction};
final class StockMovementResource extends Resource {
 protected static ?string $model=StockMovement::class; protected static ?string $modelLabel='Movimentação'; protected static ?string $pluralModelLabel='Movimentações'; protected static ?string $navigationLabel='Movimentações'; protected static string|UnitEnum|null $navigationGroup='Estoque e Almoxarifado'; protected static string|BackedEnum|null $navigationIcon='heroicon-o-arrows-right-left';
 public static function form(Schema $schema): Schema { return $schema->columns(1)->components([Section::make('Movimentação')->schema([Grid::make(['default'=>1,'md'=>2,'xl'=>4])->schema([TextInput::make('number')->label('Número')->default(fn():string=>'MOV-'.date('YmdHis'))->required(),Select::make('movement_type')->label('Tipo')->options(['in'=>'Entrada','out'=>'Saída','transfer_in'=>'Entrada por transferência','transfer_out'=>'Saída por transferência','adjustment_in'=>'Ajuste de entrada','adjustment_out'=>'Ajuste de saída'])->required(),Select::make('warehouse_id')->label('Almoxarifado')->relationship('warehouse','name')->searchable()->preload()->required(),Select::make('product_id')->label('Produto')->relationship('product','name')->searchable()->preload()->required(),TextInput::make('quantity')->label('Quantidade')->numeric()->required(),TextInput::make('unit_cost')->label('Custo unitário')->numeric()->default(0),DateTimePicker::make('occurred_at')->label('Data/hora')->default(now())->required(),Textarea::make('notes')->label('Observações')->columnSpanFull()])])]); }
 public static function table(Table $table): Table { return $table->columns([TextColumn::make('number')->label('Número')->searchable(),TextColumn::make('movement_type')->label('Tipo')->badge()->formatStateUsing(fn (?string $state):string=>str_contains((string)$state,'out')?'Saída':'Entrada')->color(fn (?string $state):string=>str_contains((string)$state,'out')?'danger':'success'),TextColumn::make('warehouse.name')->label('Almoxarifado'),TextColumn::make('product.name')->label('Produto')->searchable(),TextColumn::make('quantity')->label('Quantidade')->numeric(decimalPlaces:4),TextColumn::make('total_cost')->label('Valor total')->money('BRL',locale:'pt_BR'),TextColumn::make('occurred_at')->label('Data')->dateTime('d/m/Y H:i')])->recordActions([EditAction::make()->label('Editar')]); }
 public static function getPages(): array { return ['index'=>ListStockMovements::route('/'),'create'=>CreateStockMovement::route('/criar'),'edit'=>EditStockMovement::route('/{record}/editar')]; }
}
