<?php
declare(strict_types=1);
namespace App\Filament\Resources\StockRequests;
use App\Filament\Resources\StockRequests\Pages\{CreateStockRequest,EditStockRequest,ListStockRequests};
use App\Modules\Inventory\Domain\Models\StockRequest;
use BackedEnum; use UnitEnum; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Schemas\Components\{Grid,Section};
use Filament\Forms\Components\{DateTimePicker,Select,Textarea,TextInput}; use Filament\Tables\Table; use Filament\Tables\Columns\TextColumn; use Filament\Actions\{BulkActionGroup,DeleteBulkAction,EditAction};
final class StockRequestResource extends Resource {
 protected static ?string $model=StockRequest::class; protected static ?string $modelLabel='Requisição de estoque'; protected static ?string $pluralModelLabel='Requisições de estoque'; protected static ?string $navigationLabel='Requisições de estoque'; protected static string|UnitEnum|null $navigationGroup='Estoque e Almoxarifado'; protected static string|BackedEnum|null $navigationIcon='heroicon-o-clipboard-document-list';
 public static function form(Schema $schema): Schema { return $schema->columns(1)->components([Section::make('Requisição')->schema([Grid::make(['default'=>1,'md'=>2,'xl'=>4])->schema([
 TextInput::make('number')->label('Número')->default(fn(): string=>'REQ-'.date('YmdHis'))->required(), Select::make('warehouse_id')->label('Almoxarifado')->relationship('warehouse','name')->searchable()->preload()->required(), Select::make('purpose')->label('Finalidade')->options(['consumption'=>'Consumo','work_order'=>'Ordem de serviço','production'=>'Produção','transfer'=>'Transferência','other'=>'Outros'])->default('consumption')->required(), Select::make('status')->label('Status')->options(['draft'=>'Rascunho','pending'=>'Pendente','approved'=>'Aprovada','partially_fulfilled'=>'Atendida parcialmente','fulfilled'=>'Atendida','cancelled'=>'Cancelada'])->default('draft')->required(), DateTimePicker::make('requested_at')->label('Solicitada em')->default(now())->required(), Textarea::make('notes')->label('Observações')->rows(4)->columnSpanFull()
 ])])]); }
 public static function table(Table $table): Table { return $table->columns([TextColumn::make('number')->label('Número')->searchable()->sortable(),TextColumn::make('warehouse.name')->label('Almoxarifado')->searchable(),TextColumn::make('purpose')->label('Finalidade')->badge()->formatStateUsing(fn (?string $state): string=>match($state){'work_order'=>'Ordem de serviço','production'=>'Produção','transfer'=>'Transferência','other'=>'Outros',default=>'Consumo'}),TextColumn::make('status')->label('Status')->badge()->formatStateUsing(fn (?string $state): string=>match($state){'pending'=>'Pendente','approved'=>'Aprovada','partially_fulfilled'=>'Parcial','fulfilled'=>'Atendida','cancelled'=>'Cancelada',default=>'Rascunho'}),TextColumn::make('requested_at')->label('Solicitada em')->dateTime('d/m/Y H:i')->sortable()])->recordActions([EditAction::make()->label('Editar')])->toolbarActions([BulkActionGroup::make([DeleteBulkAction::make()->label('Excluir selecionados')])]); }
 public static function getPages(): array { return ['index'=>ListStockRequests::route('/'),'create'=>CreateStockRequest::route('/criar'),'edit'=>EditStockRequest::route('/{record}/editar')]; }
}
